### ISSUE TITLE
Filtering on a date column

### ISSUE THREAD

**Issue by ProNotion** [tochoromero/vue-smart-table#106]
Do we need to implement a custom filter in order to filter on a date?

**Comment by tochoromero** [comment]
Hi, yes, anything other than sorting strings or numbers must be a custom
filter. Thankfully they are very easy to implement.

**Comment by ProNotion** [comment]
Thank you for the prompt reply - I will give it a go

**Comment by ProNotion** [comment]
@tochoromero  I have my filter implemented and it is returning true when dates match the search however no results are shown in the table?

Here are the filters passed to the table:

```
filters: {
	query: {value: '', keys: ['transactionNumber', 'transactionDescription', 'transactionAmount']},
	transactionDate:  { value: "", keys: ["transactionDate"], custom: this.dateFilter}
}
```
And here is the filter:

```
dateFilter (filterValue, row) {
  let m = moment(filterValue);
  
  // Invalid date so won't apply filter
  if(!m.isValid()) return true;
  
  let transactionDate = moment(row.transactionDate);
  let searchDate = moment(filterValue, ["DD-MM-YYYY", "DD/MM/YYYY"]);
  
  if(!transactionDate.isValid() || !searchDate.isValid()) return true;
  
  return transactionDate.format('YYYY-MM-DD') === searchDate.format('YYYY-MM-DD');
}
```

Having stepped through the debugger I can see a true value is returned. What am I missing?

**Comment by tochoromero** [comment]
Hey, where is the function returning true? Does it reach the last return
statement?

**Comment by ProNotion** [comment]
Yes, I had my breakpoint set on `return transactionDate.format('YYYY-MM-DD') === searchDate.format('YYYY-MM-DD');` to ensure we had valid dates for comparison and that they were in fact returning a truthy value.

**Comment by ProNotion** [comment]
@tochoromero Did you have any ideas why this might be the case?

**Comment by ProNotion** [comment]
Moved on to use another component instead
